[workspace]
resolver = "2"
members = [
  "evm-decode",
  "cast",
  "evm-validate",
  "core",
]

[workspace.dependencies]
arrow = "54"
alloy-dyn-abi = "0.8"
alloy-json-abi = "0.8"
alloy-primitives = "0.8"
ruint = "1"
anyhow = "1"
log = "0.4"
faster-hex = "0.10"

